import type { GenreType } from "./types";

export type AdCategory =
	| "web" // Web hosting, guestbooks, hit counters
	| "retro" // MIDI, dial-up, Y2K stuff
	| "gaming" // Retro games, arcade
	| "chill" // Elevator music, coffee, relaxation
	| "underground" // Pirate radio, secret files, hacker stuff
	| "chaos" // Construction, rave, energy drinks
	| "general"; // Universal nostalgic stuff

export type Commercial = {
	product: string;
	categories: AdCategory[];
	lines: string[];
};

export type RadioStation = {
	name: string;
	tagline: string;
	frequency: string;
	preferredGenres: GenreType[];
	adCategories: AdCategory[];
	djNames: string[];
	jingles: string[];
	stationIds: string[];
	adBreakIntros: string[];
	adBreakOutros: string[];
	color: string;
};
export const stations: RadioStation[] = [
	{
		name: "RACCOON FM",
		tagline: "Nocturnal Beats for Night Owls",
		frequency: "97.3",
		preferredGenres: ["lofi", "ambient", "vaporwave", "synthwave"],
		adCategories: ["chill", "chaos", "general"],
		djNames: [
			"DJ Trash Panda",
			"The Masked Bandit",
			"Ringtail Rick",
			"Midnight Marauder",
			"Garbage Groove Gary",
		],
		jingles: [
			"RACCOON FM - Nocturnal beats for night owls",
			"You're listening to RACCOON FM, ninety seven point three",
			"RACCOON FM - Where the dumpster divers dance",
			"Trash never sounded so good - RACCOON FM",
			"RACCOON FM - Broadcasting from behind the bins",
		],
		stationIds: [
			"This is RACCOON FM",
			"You're tuned to ninety seven three, RACCOON FM",
			"RACCOON FM, your nocturnal companion",
			"Keep it locked on RACCOON FM",
		],
		adBreakIntros: [
			"Time for a word from our sponsors, don't go raiding any bins",
			"Quick break, grab a snack from the trash",
			"Sponsors make this dumpster fire possible",
		],
		adBreakOutros: [
			"Back to the nocturnal beats",
			"Sponsors fed, back to the music",
			"Thank you sponsors, now more trash bangers",
		],
		color: "#7a5230",
	},
	{
		name: "GeoCities Radio",
		tagline: "The Sound of the World Wide Web",
		frequency: "95.6",
		preferredGenres: ["midi", "chiptune", "synthwave"],
		adCategories: ["web", "retro", "general"],
		djNames: [
			"DJ Webmaster",
			"The HTML Kid",
			"Blink Tag Barry",
			"Marquee Mike",
			"Frames Frank",
		],
		jingles: [
			"GeoCities Radio - Best viewed in Netscape Navigator",
			"You're listening to GeoCities Radio, streaming at 56k",
			"GeoCities Radio - Under construction since 1996",
			"Please sign our guestbook - GeoCities Radio",
			"GeoCities Radio - Now with visitor counter",
		],
		stationIds: [
			"This is GeoCities Radio",
			"GeoCities Radio, broadcasting on the information superhighway",
			"You've got radio - GeoCities Radio",
			"GeoCities Radio, your dial-up destination",
		],
		adBreakIntros: [
			"Please wait while we load these messages",
			"Buffering sponsors, please stand by",
			"A word from our webmasters",
		],
		adBreakOutros: [
			"Download complete, back to the music",
			"Sponsors loaded, resuming broadcast",
			"Thank you for waiting, here's more music",
		],
		color: "#0000ff",
	},
	{
		name: "RAVE.NET",
		tagline: "Maximum BPM Minimum Sleep",
		frequency: "140.0",
		preferredGenres: ["happycore", "trance", "techno"],
		adCategories: ["chaos", "general"],
		djNames: [
			"DJ Serotonin",
			"Bass Face Betty",
			"Hardcore Hannah",
			"The BPM Beast",
			"Glowstick Gary",
		],
		jingles: [
			"RAVE DOT NET - Maximum BPM minimum sleep",
			"You're locked into RAVE DOT NET, one forty point oh",
			"RAVE DOT NET - Where every night is Saturday",
			"Hands up for RAVE DOT NET",
			"RAVE DOT NET - Loading euphoria please wait",
		],
		stationIds: [
			"This is RAVE DOT NET",
			"RAVE DOT NET, no sleep till bandwidth",
			"You're on RAVE DOT NET",
			"RAVE DOT NET, your portal to the plur",
		],
		adBreakIntros: [
			"HYDRATION BREAK, drink some water",
			"Time to catch your breath, sponsors incoming",
			"Quick break, the bass will return",
		],
		adBreakOutros: [
			"BASS RESTORED, let's go",
			"Sponsors complete, DROP incoming",
			"Back to maximum BPM",
		],
		color: "#ff00ff",
	},
	{
		name: "Aesthetic FM",
		tagline: "It's All In Your Head",
		frequency: "80.0",
		preferredGenres: ["vaporwave", "ambient", "lofi"],
		adCategories: ["chill", "retro", "general"],
		djNames: [
			"DJ Macintosh Plus",
			"Mall Walker Mike",
			"Sunset Sarah",
			"The Marble Man",
			"Elevator Earl",
		],
		jingles: [
			"Aesthetic FM - It's all in your head",
			"You're drifting with Aesthetic FM, eighty point oh",
			"Aesthetic FM - Memories of a mall that never was",
			"Aesthetic FM - Please enjoy your stay",
			"Aesthetic FM - Now loading nostalgia",
		],
		stationIds: [
			"This is Aesthetic FM",
			"Aesthetic FM, your virtual paradise",
			"You're floating with Aesthetic FM",
			"Aesthetic FM, the sound of empty malls",
		],
		adBreakIntros: [
			"A message from our sponsors in the eternal mall",
			"Please enjoy these messages",
			"Elevator stopping at: advertisements",
		],
		adBreakOutros: [
			"Returning to the eternal playlist",
			"Sponsors complete, resume floating",
			"Back to the marble halls",
		],
		color: "#ff71ce",
	},
	{
		name: "Nocturnal Scribbles Radio",
		tagline: "Late Night Thoughts, Early Morning Beats",
		frequency: "3.33",
		preferredGenres: ["lofi", "ambient", "synthwave", "vaporwave"],
		adCategories: ["chill", "underground", "general"],
		djNames: [
			"The Night Scribbler",
			"DJ Insomnia",
			"3AM Thoughts",
			"The Raccoon",
			"Caffeine Chris",
		],
		jingles: [
			"Nocturnal Scribbles Radio - Late night thoughts, early morning beats",
			"You're listening to Nocturnal Scribbles Radio, three thirty three AM",
			"Nocturnal Scribbles Radio - For when sleep is just a suggestion",
			"Nocturnal Scribbles Radio - Powered by caffeine and chaos",
			"Nocturnal Scribbles Radio - Where deadlines go to die",
		],
		stationIds: [
			"This is Nocturnal Scribbles Radio",
			"Nocturnal Scribbles Radio, broadcasting from the void",
			"You're up late with Nocturnal Scribbles Radio",
			"Nocturnal Scribbles Radio, no sleep no problem",
		],
		adBreakIntros: [
			"Quick break, the raccoon needs caffeine",
			"Sponsors, because sleep is expensive",
			"A word from people who also don't sleep",
		],
		adBreakOutros: [
			"Caffeine acquired, back to scribbling",
			"Sponsors done, more late night vibes",
			"Thank you sponsors, back to the void",
		],
		color: "#4a0080",
	},
	{
		name: "ELEVATOR.FM",
		tagline: "Going Up",
		frequency: "88.8",
		preferredGenres: ["vaporwave", "ambient", "midi"],
		adCategories: ["chill", "general"],
		djNames: [
			"The Lobby Host",
			"Floor 13 Frank",
			"Muzak Martha",
			"Soft Jazz Steve",
			"The Elevator Operator",
		],
		jingles: [
			"ELEVATOR FM - Going up",
			"You're riding with ELEVATOR FM, eighty eight point eight",
			"ELEVATOR FM - Please hold, your floor is approaching",
			"ELEVATOR FM - Smooth sounds for smooth rides",
			"ELEVATOR FM - No sudden movements please",
		],
		stationIds: [
			"This is ELEVATOR FM",
			"ELEVATOR FM, now arriving at your floor",
			"You're floating with ELEVATOR FM",
			"ELEVATOR FM, the music between floors",
		],
		adBreakIntros: [
			"Please hold, messages incoming",
			"The elevator is stopping for messages",
			"Going down to the sponsor floor",
		],
		adBreakOutros: [
			"Resuming your floor",
			"Sponsors complete, going up",
			"Back to smooth sounds",
		],
		color: "#c0a080",
	},
	{
		name: "CONSTRUCTION ZONE",
		tagline: "Hard Hats Required",
		frequency: "110.1",
		preferredGenres: ["techno", "trance", "synthwave", "happycore"],
		adCategories: ["chaos", "web", "general"],
		djNames: [
			"Jackhammer Jack",
			"DJ Demolition",
			"Steel Beam Steve",
			"The Foreman",
			"Concrete Carl",
		],
		jingles: [
			"CONSTRUCTION ZONE - Hard hats required",
			"You're in the CONSTRUCTION ZONE, one ten point one",
			"CONSTRUCTION ZONE - Always under construction",
			"CONSTRUCTION ZONE - Caution, loud noises ahead",
			"CONSTRUCTION ZONE - Building beats from the ground up",
		],
		stationIds: [
			"This is CONSTRUCTION ZONE",
			"CONSTRUCTION ZONE, pardon our dust",
			"You're in the CONSTRUCTION ZONE",
			"CONSTRUCTION ZONE, coming soon",
		],
		adBreakIntros: [
			"HARD HAT AREA, commercial zone ahead",
			"Construction pause for sponsors",
			"Building a better break",
		],
		adBreakOutros: [
			"Construction resumes",
			"Back to building beats",
			"Hard hats on, music returns",
		],
		color: "#ff6600",
	},
	{
		name: "WEBRING RADIO",
		tagline: "Previous, Next, Random",
		frequency: "99.9",
		preferredGenres: [
			"chiptune",
			"ambient",
			"synthwave",
			"lofi",
			"techno",
			"trance",
			"midi",
			"happycore",
			"vaporwave",
		],
		adCategories: ["web", "retro", "general"],
		djNames: [
			"Link Exchange Larry",
			"DJ Random",
			"The Ring Master",
			"Navigator Nancy",
			"Hop Skip Harry",
		],
		jingles: [
			"WEBRING RADIO - Previous, next, random",
			"You're surfing with WEBRING RADIO, ninety nine point nine",
			"WEBRING RADIO - All genres, all the time",
			"WEBRING RADIO - You never know what's next",
			"WEBRING RADIO - Part of a complete internet",
		],
		stationIds: [
			"This is WEBRING RADIO",
			"WEBRING RADIO, connecting sites since 1994",
			"You're linked to WEBRING RADIO",
			"WEBRING RADIO, hop on the ring",
		],
		adBreakIntros: [
			"Hopping to the sponsor ring",
			"Next site: advertisements",
			"Random sponsor selected",
		],
		adBreakOutros: [
			"Back to the ring",
			"Sponsors complete, next random song",
			"Returning to regular webring",
		],
		color: "#00cc00",
	},
	{
		name: "MIDNIGHT.GOV",
		tagline: "Numbers. Only Numbers.",
		frequency: "0.00",
		preferredGenres: ["ambient"],
		adCategories: ["underground"],
		djNames: [
			"Agent Frequency",
			"The Numbers Lady",
			"Cipher Seven",
			"Station Chief",
			"The Monotone",
		],
		jingles: [
			"MIDNIGHT GOV - Numbers. Only numbers.",
			"You are receiving MIDNIGHT GOV, zero zero zero",
			"MIDNIGHT GOV - Message begins at the tone",
			"MIDNIGHT GOV - The following is for recipient seven four two",
			"MIDNIGHT GOV - Standby for transmission",
		],
		stationIds: [
			"This is MIDNIGHT GOV",
			"MIDNIGHT GOV, broadcasting on schedule",
			"You are receiving MIDNIGHT GOV",
			"MIDNIGHT GOV, message ends",
		],
		adBreakIntros: [
			"Transmission interrupted for messages",
			"The following is authorized content",
			"Message begins",
		],
		adBreakOutros: [
			"Message ends, resuming transmission",
			"Regular broadcast continues",
			"Numbers resume",
		],
		color: "#001100",
	},
	{
		name: "PIXEL PARTY",
		tagline: "Insert Coin to Continue",
		frequency: "8.00",
		preferredGenres: ["chiptune", "midi", "happycore"],
		adCategories: ["gaming", "retro", "general"],
		djNames: [
			"Player One",
			"8-Bit Betty",
			"DJ Game Over",
			"The High Score",
			"Cartridge Chris",
		],
		jingles: [
			"PIXEL PARTY - Insert coin to continue",
			"You're playing PIXEL PARTY, eight point oh oh",
			"PIXEL PARTY - New high score",
			"PIXEL PARTY - Select your character",
			"PIXEL PARTY - Level up your ears",
		],
		stationIds: [
			"This is PIXEL PARTY",
			"PIXEL PARTY, press start",
			"You're tuned to PIXEL PARTY",
			"PIXEL PARTY, game on",
		],
		adBreakIntros: [
			"INSERT COIN for sponsors",
			"Loading advertisement level",
			"Bonus sponsor round",
		],
		adBreakOutros: [
			"GAME RESUME",
			"Sponsor level complete",
			"Back to the arcade",
		],
		color: "#00ff00",
	},
	{
		name: "Y2K PANIC FM",
		tagline: "The Countdown Never Ends",
		frequency: "19.99",
		preferredGenres: ["trance", "happycore", "techno"],
		adCategories: ["retro", "chaos", "general"],
		djNames: [
			"DJ Doomsday",
			"Millennium Mike",
			"Bug Hunter Betty",
			"The Y2K Kid",
			"Countdown Carl",
		],
		jingles: [
			"Y2K PANIC FM - The countdown never ends",
			"You're panicking with Y2K PANIC FM, nineteen ninety nine",
			"Y2K PANIC FM - Have you backed up your data?",
			"Y2K PANIC FM - Only 999 days until the next millennium bug",
			"Y2K PANIC FM - Party like it's December 31st",
		],
		stationIds: [
			"This is Y2K PANIC FM",
			"Y2K PANIC FM, still counting down",
			"You're surviving with Y2K PANIC FM",
			"Y2K PANIC FM, the bug is coming",
		],
		adBreakIntros: [
			"Emergency sponsor broadcast",
			"These ads are Y2K compliant, probably",
			"Quick, buy things before the crash",
		],
		adBreakOutros: [
			"Sponsors survived, back to panic",
			"Commerce complete, resume countdown",
			"Still counting down",
		],
		color: "#ff0000",
	},
	{
		name: "PIRATE RADIO",
		tagline: "Unauthorized Broadcast",
		frequency: "???",
		preferredGenres: ["techno", "synthwave", "happycore", "trance"],
		adCategories: ["underground", "chaos"],
		djNames: [
			"Captain Static",
			"The Signal Jacker",
			"Rogue Wave Rick",
			"Frequency Phantom",
			"DJ Interference",
		],
		jingles: [
			"PIRATE RADIO - Unauthorized broadcast",
			"You've found PIRATE RADIO, frequency unknown",
			"PIRATE RADIO - They can't catch us",
			"PIRATE RADIO - Broadcasting from international waters",
			"PIRATE RADIO - Tune in before we disappear",
		],
		stationIds: [
			"This is PIRATE RADIO",
			"PIRATE RADIO, you didn't hear this from us",
			"You're receiving PIRATE RADIO",
			"PIRATE RADIO, signal unstable",
		],
		adBreakIntros: [
			"Even pirates have sponsors, arrr",
			"Intercepted transmission: ads",
			"Signal hijacked for commerce",
		],
		adBreakOutros: [
			"Back to unauthorized music",
			"Sponsors walked the plank, more tunes",
			"Signal restored, resume piracy",
		],
		color: "#333333",
	},
	{
		name: "THE VOID",
		tagline: "...",
		frequency: "0.01",
		preferredGenres: ["ambient"],
		adCategories: ["underground"],
		djNames: ["...", "The Silence", "Echo", "Nobody", "The Distant One"],
		jingles: [
			"THE VOID",
			"You are listening to THE VOID",
			"THE VOID - Is anyone there?",
			"THE VOID - Hello?",
			"THE VOID - Nothing but us",
		],
		stationIds: [
			"This is THE VOID",
			"THE VOID",
			"You are in THE VOID",
			"THE VOID welcomes you",
		],
		adBreakIntros: [
			"...",
			"Messages from the void",
			"Someone is trying to sell you something",
		],
		adBreakOutros: ["...", "Returning to nothing", "Void resumes"],
		color: "#000000",
	},
	{
		name: "SHOPPING CHANNEL",
		tagline: "Call Now, Operators Standing By",
		frequency: "24.7",
		preferredGenres: ["vaporwave", "midi", "lofi"],
		adCategories: ["retro", "chill", "general"],
		djNames: [
			"Sales Associate Sally",
			"DJ Discount",
			"The Price Dropper",
			"Clearance Clarence",
			"Infomercial Ian",
		],
		jingles: [
			"SHOPPING CHANNEL - Call now, operators standing by",
			"You're shopping with the SHOPPING CHANNEL, twenty four seven",
			"SHOPPING CHANNEL - But wait, there's more",
			"SHOPPING CHANNEL - Only nineteen ninety five",
			"SHOPPING CHANNEL - Order in the next fifteen minutes",
		],
		stationIds: [
			"This is the SHOPPING CHANNEL",
			"SHOPPING CHANNEL, always open",
			"You're watching the SHOPPING CHANNEL",
			"SHOPPING CHANNEL, three easy payments",
		],
		adBreakIntros: [
			"MORE products you need",
			"But wait, there's sponsors",
			"Order now, messages follow",
		],
		adBreakOutros: [
			"But seriously, back to shopping music",
			"Sponsors complete, more products await",
			"Resume browsing",
		],
		color: "#ffcc00",
	},
	{
		name: "TEST PATTERN",
		tagline: "Please Stand By",
		frequency: "00.0",
		preferredGenres: ["ambient"],
		adCategories: ["general"],
		djNames: [
			"The Technician",
			"Color Bars Carl",
			"Tone Generator Tom",
			"The Test Signal",
			"Standby Steve",
		],
		jingles: [
			"TEST PATTERN - Please stand by",
			"You are receiving TEST PATTERN, zero zero zero",
			"TEST PATTERN - Normal programming will resume shortly",
			"TEST PATTERN - This is a test",
			"TEST PATTERN - Do not adjust your set",
		],
		stationIds: [
			"This is TEST PATTERN",
			"TEST PATTERN, calibrating",
			"You are receiving TEST PATTERN",
			"TEST PATTERN, end of broadcast day",
		],
		adBreakIntros: [
			"Testing advertisement broadcast",
			"Sponsor calibration in progress",
			"Please stand by for messages",
		],
		adBreakOutros: [
			"Advertisement test complete",
			"Resuming normal test pattern",
			"Calibration continues",
		],
		color: "#888888",
	},
	{
		name: "HOLD MUSIC",
		tagline: "Your Call Is Important To Us",
		frequency: "1.800",
		preferredGenres: ["vaporwave", "ambient", "lofi", "midi"],
		adCategories: ["chill", "general"],
		djNames: [
			"Representative Rachel",
			"Queue Manager Quinn",
			"The Hold Master",
			"Waiting Room Wendy",
			"DJ Estimated Wait Time",
		],
		jingles: [
			"HOLD MUSIC - Your call is important to us",
			"You're holding with HOLD MUSIC, one eight hundred",
			"HOLD MUSIC - Please continue to hold",
			"HOLD MUSIC - A representative will be with you shortly",
			"HOLD MUSIC - You are caller number forty seven",
		],
		stationIds: [
			"This is HOLD MUSIC",
			"HOLD MUSIC, still waiting",
			"You're on hold with HOLD MUSIC",
			"HOLD MUSIC, thank you for your patience",
		],
		adBreakIntros: [
			"Your call is important, here are some messages",
			"Please continue to hold for sponsors",
			"Estimated wait: one ad break",
		],
		adBreakOutros: [
			"Thank you for holding, resuming music",
			"Sponsors complete, continue waiting",
			"Back to hold music",
		],
		color: "#6699cc",
	},
	{
		name: "ARCADE ZONE",
		tagline: "Insert Quarters Here",
		frequency: "16.00",
		preferredGenres: ["chiptune", "midi", "happycore"],
		adCategories: ["gaming", "retro", "general"],
		djNames: [
			"Player Two",
			"Quarter Queen",
			"DJ Continue?",
			"The Combo King",
			"Joystick Jenny",
		],
		jingles: [
			"ARCADE ZONE - Insert quarters here",
			"You're gaming with ARCADE ZONE, sixteen point oh oh",
			"ARCADE ZONE - Winners don't use save states",
			"ARCADE ZONE - Game over? Never heard of it",
			"ARCADE ZONE - High scores and higher BPM",
		],
		stationIds: [
			"This is ARCADE ZONE",
			"ARCADE ZONE, ready player one",
			"You're in the ARCADE ZONE",
			"ARCADE ZONE, no quarters no problems",
		],
		adBreakIntros: [
			"Continue? Insert sponsor",
			"Advertisement bonus round",
			"Power-up: commercials",
		],
		adBreakOutros: [
			"CONTINUE? YES, back to game",
			"Sponsor round complete",
			"Resume play",
		],
		color: "#ff00ff",
	},
	{
		name: "DARK.NET",
		tagline: "We Know Your IP Address",
		frequency: "66.6",
		preferredGenres: ["techno", "ambient"],
		adCategories: ["underground"],
		djNames: [
			"Anonymous",
			"The Hacker",
			"Root Access Rita",
			"Zero Day Dave",
			"Packet Sniffer Pete",
		],
		jingles: [
			"DARK DOT NET - We know your IP address",
			"You've connected to DARK DOT NET, sixty six point six",
			"DARK DOT NET - Your firewall can't save you",
			"DARK DOT NET - Encryption is just a suggestion",
			"DARK DOT NET - Welcome to the deep web",
		],
		stationIds: [
			"This is DARK DOT NET",
			"DARK DOT NET, connection established",
			"You're logged into DARK DOT NET",
			"DARK DOT NET, trace in progress",
		],
		adBreakIntros: [
			"Encrypted sponsors incoming",
			"These ads cannot be traced",
			"Anonymous commerce time",
		],
		adBreakOutros: [
			"Encryption restored, back to beats",
			"Sponsors purged, resume transmission",
			"Connection secure, music resumes",
		],
		color: "#003300",
	},
	{
		name: "CAFE.FM",
		tagline: "Take Your Time",
		frequency: "45.0",
		preferredGenres: ["lofi"],
		adCategories: ["chill", "general"],
		djNames: [
			"Barista Brian",
			"The Espresso Express",
			"Latte Larry",
			"DJ Decaf",
			"Mocha Mike",
		],
		jingles: [
			"CAFE FM - Take your time",
			"You're chilling with CAFE FM, forty five point oh",
			"CAFE FM - No rush, no deadlines",
			"CAFE FM - Like a warm cup on a rainy day",
			"CAFE FM - Stay as long as you like",
		],
		stationIds: [
			"This is CAFE FM",
			"CAFE FM, always brewing",
			"You're relaxing with CAFE FM",
			"CAFE FM, refills are free",
		],
		adBreakIntros: [
			"Refill break, here are some messages",
			"While your coffee cools, some sponsors",
			"Take a sip, hear some ads",
		],
		adBreakOutros: [
			"Coffee refilled, back to chill",
			"Sponsors sipped, more vibes",
			"Resume relaxation",
		],
		color: "#8b4513",
	},
	{
		name: "DUMPSTER DIVE FM",
		tagline: "We Eat Everything",
		frequency: "3.AM",
		preferredGenres: [
			"chiptune",
			"ambient",
			"synthwave",
			"lofi",
			"techno",
			"trance",
			"midi",
			"happycore",
			"vaporwave",
		],
		adCategories: [
			"web",
			"retro",
			"gaming",
			"chill",
			"underground",
			"chaos",
			"general",
		],
		djNames: [
			"DJ Trash Panda",
			"The Garbage Gourmet",
			"Leftovers Larry",
			"Dumpster Diva",
			"The Masked Bandit",
			"Ringtail Ricky",
			"Scraps McGee",
		],
		jingles: [
			"DUMPSTER DIVE FM - We eat everything",
			"You're scavenging with DUMPSTER DIVE FM, twenty four seven",
			"DUMPSTER DIVE FM - One raccoon's trash is another's treasure",
			"DUMPSTER DIVE FM - No genre left behind",
			"DUMPSTER DIVE FM - If it makes sound, we'll play it",
		],
		stationIds: [
			"This is DUMPSTER DIVE FM",
			"DUMPSTER DIVE FM, rummaging through the genres",
			"You're digging with DUMPSTER DIVE FM",
			"DUMPSTER DIVE FM, paws in everything",
		],
		adBreakIntros: [
			"Found some ads in the trash, enjoy",
			"Scavenged sponsors incoming",
			"One raccoon's ad is another's treasure",
		],
		adBreakOutros: [
			"Ads recycled, back to diving",
			"Sponsors scavenged, more tunes",
			"Resume rummaging through genres",
		],
		color: "#5a4a3a",
	},
];
export const commercials: Commercial[] = [
	// WEB category - web hosting, guestbooks, hit counters
	{
		product: "FreeWebHosting.geo",
		categories: ["web", "general"],
		lines: [
			"Need a website? FreeWebHosting dot geo has you covered",
			"Unlimited GIFs, unlimited marquees, unlimited dreams",
			"Sign up now and get a free visitor counter",
			"FreeWebHosting dot geo - Your home on the web",
		],
	},
	{
		product: "MIDI Collection Pro",
		categories: ["web", "retro"],
		lines: [
			"Introducing MIDI Collection Pro",
			"Over ten thousand background MIDIs for your homepage",
			"From Bach to Backstreet Boys, we've got it all",
			"MIDI Collection Pro - Make your visitors wait for music",
		],
	},
	{
		product: "GuestBook Plus",
		categories: ["web"],
		lines: [
			"Are visitors signing your guestbook? They should be",
			"GuestBook Plus - Now with sparkle animations",
			"See who visited from which country",
			"GuestBook Plus - Because you need validation",
		],
	},
	{
		product: "WebRing Membership",
		categories: ["web", "general"],
		lines: [
			"Join the WebRing today",
			"Connect with fellow webmasters around the globe",
			"Previous site, next site, random site",
			"WebRing - The original social network",
		],
	},
	{
		product: "Animated GIF Warehouse",
		categories: ["web", "general"],
		lines: [
			"Welcome to the Animated GIF Warehouse",
			"Dancing babies, spinning skulls, under construction signs",
			"All the GIFs your bandwidth can handle",
			"Animated GIF Warehouse - Loading please wait",
		],
	},
	{
		product: "Cursor Trails Deluxe",
		categories: ["web"],
		lines: [
			"Make your cursor unforgettable with Cursor Trails Deluxe",
			"Stars, hearts, flames, or all three at once",
			"Your visitors will never forget where your mouse went",
			"Cursor Trails Deluxe - Because subtlety is overrated",
		],
	},
	{
		product: "Hit Counter Premium",
		categories: ["web"],
		lines: [
			"How many visitors have you had? Show them with Hit Counter Premium",
			"Multiple styles including odometer, slot machine, and flames",
			"Starts at any number you want, we won't tell",
			"Hit Counter Premium - Inflate your ego today",
		],
	},
	{
		product: "Under Construction Sign Pack",
		categories: ["web", "chaos"],
		lines: [
			"Is your page not ready yet? Show it with style",
			"Over fifty animated construction worker GIFs included",
			"Caution tape borders and hard hat clipart",
			"Under Construction Sign Pack - Coming soon since 1997",
		],
	},
	// RETRO category - dial-up, Y2K, nostalgia
	{
		product: "56K Modem Turbo",
		categories: ["retro"],
		lines: [
			"Tired of slow downloads? Try the new 56K Modem Turbo",
			"Download a single MP3 in only forty five minutes",
			"That beautiful dial-up sound means speed",
			"56K Modem Turbo - Get off the phone mom",
		],
	},
	{
		product: "Y2K Survival Kit",
		categories: ["retro", "chaos"],
		lines: [
			"The millennium bug is coming, are you prepared?",
			"Includes backup floppies, a printed copy of your bookmarks, and canned beans",
			"Don't let the year 2000 catch you off guard",
			"Y2K Survival Kit - Because your computer won't survive",
		],
	},
	{
		product: "Floppy Disk Bulk Pack",
		categories: ["retro"],
		lines: [
			"Running low on storage? Floppy Disk Bulk Pack has you covered",
			"One hundred disks, that's almost one hundred and forty megabytes",
			"Pre-formatted and ready for your important files",
			"Floppy Disk Bulk Pack - Stack them high",
		],
	},
	{
		product: "Screensaver Spectacular",
		categories: ["retro", "general"],
		lines: [
			"Protect your CRT with Screensaver Spectacular",
			"Flying toasters, 3D pipes, and star fields included",
			"Password protection to keep siblings out",
			"Screensaver Spectacular - Burn-in is forever",
		],
	},
	// GAMING category - arcade, retro games
	{
		product: "Retro Game Cartridge Cleaner",
		categories: ["gaming"],
		lines: [
			"Games not working? Don't blow on them",
			"Retro Game Cartridge Cleaner safely removes dust and grime",
			"Works on all cartridge sizes and formats",
			"Retro Game Cartridge Cleaner - Insert coin to continue",
		],
	},
	{
		product: "Arcade Token Exchange",
		categories: ["gaming"],
		lines: [
			"Out of quarters? Visit the Arcade Token Exchange",
			"We turn your bills into dreams",
			"Bulk rates available for serious gamers",
			"Arcade Token Exchange - One more try",
		],
	},
	{
		product: "High Score Registry",
		categories: ["gaming"],
		lines: [
			"Did you get the high score? Prove it",
			"High Score Registry keeps your achievements immortal",
			"Includes certificate suitable for framing",
			"High Score Registry - Your initials belong here",
		],
	},
	{
		product: "Joystick Restoration Service",
		categories: ["gaming", "retro"],
		lines: [
			"Is your joystick drifting? We can fix that",
			"Joystick Restoration Service brings controllers back to life",
			"Microswitches replaced, springs tightened, buttons de-gunked",
			"Joystick Restoration Service - Play like new",
		],
	},
	{
		product: "Cheat Code Compendium",
		categories: ["gaming"],
		lines: [
			"Up up down down left right left right B A start",
			"Cheat Code Compendium has every secret for every game",
			"Infinite lives, level skips, hidden characters revealed",
			"Cheat Code Compendium - We won't tell if you won't",
		],
	},
	// CHILL category - coffee, relaxation, muzak
	{
		product: "Elevator Music Collection",
		categories: ["chill"],
		lines: [
			"Introducing the Elevator Music Collection",
			"Forty seven hours of smooth jazz and soft rock",
			"Perfect for your lobby, waiting room, or hold system",
			"Elevator Music Collection - Going up",
		],
	},
	{
		product: "Premium Hold Music License",
		categories: ["chill"],
		lines: [
			"Tired of silence while your callers wait?",
			"Premium Hold Music License includes royalty-free smooth jazz",
			"Callers will actually enjoy being on hold",
			"Premium Hold Music - Your call is important to us",
		],
	},
	{
		product: "Artisan Bean Subscription",
		categories: ["chill"],
		lines: [
			"Wake up to Artisan Bean Subscription",
			"Single origin, fair trade, hand roasted weekly",
			"Delivered to your door before you run out",
			"Artisan Bean Subscription - Life's too short for bad coffee",
		],
	},
	{
		product: "Rain Sounds Premium",
		categories: ["chill"],
		lines: [
			"Can't sleep? Try Rain Sounds Premium",
			"Twelve hours of continuous gentle rainfall",
			"Optional thunder, optional distant trains",
			"Rain Sounds Premium - Drift away",
		],
	},
	{
		product: "Lo-Fi Study Beats Vol. 47",
		categories: ["chill", "general"],
		lines: [
			"Need to focus? Lo-Fi Study Beats Vol. forty seven is here",
			"Four hours of chill beats to relax and study to",
			"Vinyl crackle and jazz piano included at no extra cost",
			"Lo-Fi Study Beats - The raccoon girl approves",
		],
	},
	{
		product: "Ambient Soundscapes Collection",
		categories: ["chill"],
		lines: [
			"Escape reality with Ambient Soundscapes Collection",
			"Forest streams, ocean waves, empty malls at closing time",
			"Perfect for meditation, sleep, or pretending to work",
			"Ambient Soundscapes - Be somewhere else",
		],
	},
	// UNDERGROUND category - hacker, secret, pirate
	{
		product: "Secret Files Monthly",
		categories: ["underground"],
		lines: [
			"What are they hiding from you? Find out with Secret Files Monthly",
			"Classified documents, forbidden frequencies, and hidden truths",
			"Delivered in a plain brown envelope",
			"Secret Files Monthly - The truth is out there on the internet",
		],
	},
	{
		product: "Pirate Radio Starter Kit",
		categories: ["underground", "chaos"],
		lines: [
			"Ever wanted to broadcast your own station?",
			"Pirate Radio Starter Kit includes everything you need",
			"Transmitter, antenna, and plausible deniability guide",
			"Pirate Radio Starter Kit - We never had this conversation",
		],
	},
	{
		product: "Anonymous VPN Service",
		categories: ["underground"],
		lines: [
			"Who's watching your internet traffic? Not anymore",
			"Anonymous VPN Service tunnels through seven countries",
			"No logs, no questions, no trace",
			"Anonymous VPN Service - You were never here",
		],
	},
	{
		product: "Encrypted Email Plus",
		categories: ["underground"],
		lines: [
			"Is your email really private? It should be",
			"Encrypted Email Plus uses military grade encryption",
			"Self-destructing messages available on request",
			"Encrypted Email Plus - They can't read what they can't decrypt",
		],
	},
	{
		product: "Signal Jammer Portable",
		categories: ["underground"],
		lines: [
			"Need some radio silence? Signal Jammer Portable delivers",
			"Blocks all frequencies in a fifty meter radius",
			"Disclaimer: may be illegal in your jurisdiction",
			"Signal Jammer Portable - Quiet at last",
		],
	},
	{
		product: "Numbers Station Decoder Ring",
		categories: ["underground"],
		lines: [
			"What do the numbers mean? Find out",
			"Numbers Station Decoder Ring reveals hidden messages",
			"Includes frequency guide and listening schedule",
			"Numbers Station Decoder Ring - The message is for you",
		],
	},
	// CHAOS category - rave, energy, construction
	{
		product: "Energy Drink Subscription Box",
		categories: ["chaos"],
		lines: [
			"Sleep is for the weak, subscribe to Energy Drink Subscription Box",
			"Twelve cans of pure caffeinated chaos every month",
			"Warning: may cause heart palpitations and poor decisions",
			"Energy Drink Subscription - Sleep when you're dead",
		],
	},
	{
		product: "Foam Party Supplies",
		categories: ["chaos"],
		lines: [
			"Turn any room into a foam party",
			"Foam Party Supplies includes industrial foam cannon",
			"Cleans up... eventually",
			"Foam Party Supplies - Why? Why not",
		],
	},
	{
		product: "Neon Light Warehouse",
		categories: ["chaos", "retro"],
		lines: [
			"Light up your life with Neon Light Warehouse",
			"Pink, blue, purple, and colors that don't exist yet",
			"Perfect for bedrooms, streams, and underground raves",
			"Neon Light Warehouse - Glow with us",
		],
	},
	{
		product: "Strobe Light Deluxe",
		categories: ["chaos"],
		lines: [
			"Flash into the future with Strobe Light Deluxe",
			"Adjustable speed from 'dance party' to 'interrogation'",
			"Warning: epilepsy risk, do not operate machinery",
			"Strobe Light Deluxe - Reality is intermittent",
		],
	},
	{
		product: "Industrial Ear Plugs",
		categories: ["chaos", "general"],
		lines: [
			"Protect what's left of your hearing",
			"Industrial Ear Plugs rated for one hundred forty decibels",
			"Comfortable enough for twelve hour rave sessions",
			"Industrial Ear Plugs - What? What?",
		],
	},
	// GENERAL / RACCOON category - universal, nocturnal
	{
		product: "Trash Can Lid Locks",
		categories: ["chaos", "general"],
		lines: [
			"Tired of mysterious visitors raiding your bins?",
			"Trash Can Lid Locks keep your garbage where it belongs",
			"Warning: will not stop determined raccoons",
			"Trash Can Lid Locks - They'll find a way anyway",
		],
	},
	{
		product: "Nocturnal Night Vision Goggles",
		categories: ["underground", "general"],
		lines: [
			"See what the raccoons see with Nocturnal Night Vision Goggles",
			"Perfect for 3AM dumpster reconnaissance",
			"Spot the best scraps before your neighbors do",
			"Nocturnal Night Vision Goggles - The night is young",
		],
	},
	{
		product: "Opposable Thumbs Monthly",
		categories: ["general"],
		lines: [
			"Learn what raccoons already know",
			"Opposable Thumbs Monthly teaches you to open anything",
			"Latches, locks, and lid techniques revealed",
			"Opposable Thumbs Monthly - Grip it and rip it",
		],
	},
	{
		product: "Forbidden Cat Adoption Agency",
		categories: ["chaos", "general"],
		lines: [
			"Not ready for a regular cat? Try a forbidden one",
			"Raccoons, possums, and other spicy houseguests available",
			"All animals come pre-trained to knock things over at 3AM",
			"Forbidden Cat Adoption Agency - Hissing means love",
		],
	},
	{
		product: "Dumpster Diving Certification Course",
		categories: ["chaos", "general"],
		lines: [
			"Turn trash into treasure with our certified program",
			"Learn from the masters: actual raccoons",
			"Includes laminated ID card and tiny headlamp",
			"Dumpster Diving Certification - One creature's trash",
		],
	},
	{
		product: "Possum Playing Dead Academy",
		categories: ["chill", "general"],
		lines: [
			"Avoid your problems the possum way",
			"Our twelve week course teaches authentic death simulation",
			"Guaranteed to fool predators and awkward social situations",
			"Possum Playing Dead Academy - Just lie there",
		],
	},
];
export const guestbookEntries = [
	{ name: "CoolDude1997", message: "Awesome site! Check out mine!" },
	{
		name: "xX_DarkAngel_Xx",
		message: "I love your page, we should link exchange",
	},
	{ name: "WebMaster2000", message: "Great use of the blink tag" },
	{ name: "MoonWolf99", message: "Your MIDI is fire, what song is that?" },
	{
		name: "CyberKitty",
		message: "Signed your guestbook, please sign mine back",
	},
	{
		name: "NetSurfer",
		message: "Found you through the webring, staying for the vibes",
	},
	{ name: "Anonymous", message: "First!" },
	{ name: "HTMLHero", message: "Love the frames layout, very professional" },
	{ name: "PixelPrincess", message: "Your GIF collection is amazing" },
	{ name: "MidnightCoder", message: "3AM and I'm still browsing this page" },
	{ name: "TrashPandaFan", message: "Fellow raccoon appreciator here" },
	{ name: "RetroGamer64", message: "This takes me back to the good old days" },
	{ name: "NocturnalNinja", message: "Love the late night aesthetic" },
	{ name: "GeoCitizen", message: "Proud neighbor from the same block" },
	{ name: "BlinkyMcBlink", message: "Can you add more marquees?" },
	{ name: "DialUpDave", message: "Worth the 5 minute load time" },
	{ name: "Y2KSurvivor", message: "Glad the internet didn't end" },
	{ name: "FramesetFred", message: "No frames? No problem, still cool" },
	{ name: "RaccoonRicky", message: "Found this site while looking for bins" },
	{ name: "xX_TrashPanda_Xx", message: "This page is garbage, I love it" },
	{ name: "PossumPaul", message: "Played dead for 20 minutes, still loading" },
	{
		name: "ForbiddenCatLover",
		message: "My raccoon typed this with his little hands",
	},
	{ name: "DumpsterDiver99", message: "Five stars, would scavenge again" },
	{ name: "NightCreature", message: "The 3AM vibes are immaculate" },
	{ name: "BanditMask", message: "Nice site, I'm stealing the CSS" },
	{ name: "GarbageGourmet", message: "Finally, a page with taste" },
	{ name: "RingtailRider", message: "Knocked over three bins getting here" },
	{ name: "HissingPossum", message: "I'm not dead I'm just loading your page" },
	{
		name: "TrashCatOfficial",
		message: "Raccoons are just cats with crime energy",
	},
	{
		name: "MidnightSnacker",
		message: "Your page pairs well with leftover pizza",
	},
	{
		name: "SpicyKitten",
		message: "Adopted a raccoon, no regrets, many scratches",
	},
	{ name: "BinChicken", message: "Ibis solidarity from Australia" },
	{ name: "UrbanForager", message: "This site has strong alley cat energy" },
	{
		name: "3AMRaccoon",
		message: "Just knocked over your guestbook to sign it",
	},
];
