// Geocities-specific data - loaded only with the geocities bundle

// Every terrible font we can think of
export const geocitiesFonts = [
	// The classics
	"Comic Sans MS",
	"Papyrus",
	"Impact",
	"Jokerman",
	"Curlz MT",
	"Kristen ITC",
	// Script/handwriting nightmares
	"Brush Script MT",
	"Lucida Handwriting",
	"Bradley Hand",
	"Segoe Script",
	"Freestyle Script",
	"French Script MT",
	"Edwardian Script ITC",
	"Kunstler Script",
	"Palace Script MT",
	"Rage Italic",
	"Script MT Bold",
	"Vivaldi",
	"Vladimir Script",
	"Mistral",
	"Monotype Corsiva",
	// Display/decorative horrors
	"Copperplate",
	"Copperplate Gothic Bold",
	"Luminari",
	"Chalkduster",
	"Marker Felt",
	"Trattatello",
	"Party LET",
	"Jazz LET",
	"Herculanum",
	"Chalkboard",
	"Chalkboard SE",
	"Zapfino",
	"Snell Roundhand",
	"Apple Chancery",
	"Hoefler Text",
	// Novelty
	"Stencil",
	"Wide Latin",
	"Playbill",
	"Harrington",
	"Algerian",
	"Bauhaus 93",
	"Broadway",
	"Showcard Gothic",
	"Ravie",
	"Snap ITC",
	"Magneto",
	"Juice ITC",
	"Jokerman",
	// Oldstyle
	"Old English Text MT",
	"Blackadder ITC",
	"Castellar",
	"Engravers MT",
	"Forte",
	"Goudy Stout",
	"Imprint MT Shadow",
	"Informal Roman",
	"Matura MT Script Capitals",
	"Niagara Engraved",
	"Niagara Solid",
	"Parchment",
	"Rockwell Extra Bold",
	// Symbol fonts (actual chaos - NOT for content areas!)
	"Webdings",
	"Wingdings",
	"Wingdings 2",
	"Wingdings 3",
	"Symbol",
	"MT Extra",
	"Bookshelf Symbol 7",
	"Zapf Dingbats",
	// Monospace but make it weird
	"Courier New",
	"Lucida Console",
	"Consolas",
	"OCR A Extended",
	// Bold/heavy
	"Arial Black",
	"Franklin Gothic Heavy",
	"Haettenschweiler",
	"Elephant",
	"Felix Titling",
	"Bernard MT Condensed",
	// macOS specific
	"American Typewriter",
	"Baskerville",
	"Big Caslon",
	"Bodoni 72",
	"Cochin",
	"Didot",
	"Futura",
	"Gill Sans",
	"Helvetica Neue",
	"Optima",
	"Palatino",
	"Phosphate",
	"Rockwell",
	"Savoye LET",
	"SignPainter",
	"Skia",
	// Generic fallbacks for maximum chaos
	"cursive",
	"fantasy",
	"serif",
	"sans-serif",
	"monospace",
];

// Icon/symbol fonts that make text unreadable
const iconFonts = [
	"Webdings",
	"Wingdings",
	"Wingdings 2",
	"Wingdings 3",
	"Symbol",
	"MT Extra",
	"Bookshelf Symbol 7",
	"Zapf Dingbats",
];

// Fonts safe for actual content (excludes icon fonts)
export const geocitiesReadableFonts = geocitiesFonts.filter(
	(f) => !iconFonts.includes(f),
);

export const geocitiesBorders = [
	"dotted",
	"dashed",
	"double",
	"ridge",
	"groove",
	"outset",
	"inset",
];
